# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:year-:month-:day-:title/

# Setup
title: Ash Hall
tagline: 'A Jekyll theme'
description: 'Machine learning research engineer; Software engineer'
url: http://hyde.getpoole.com
baseurl: ashwhall.github.io

author:
  name: 'Ash Hall'

paginate: 5
paginate_dir: 'posts'
paginate_path: 'posts/page:num'
excerpt_separator: <!--more-->

sidebar_links:
  - title: 'Home'
    url: '/'
  - title: 'About'
    url: '/about/'
  - title: 'Papers'
    url: '/papers/'
  - title: 'Posts'
    url: '/posts/'
  # TODO: Add projects
  # - title: "Projects"
  #   url: "/projects/"

collections:
  projects:
    output: true
    permalink: /projects/:path/

social_links:
  - name: 'Email'
    url: 'mailto:ashwhall@gmail.com'
    faicon: 'envelope'
  - name: 'Phone'
    url: 'tel:(+61) 434464390'
    faicon: 'phone'
  - name: 'Github'
    url: 'https://github.com/ashwhall'
    faicon: 'github'
  - name: 'Gitlab'
    url: 'https://gitlab.com/ashwhall'
    faicon: 'gitlab'
  - name: 'LinkedIn'
    url: 'https://linkedin.com/in/ashwhall'
    faicon: 'linkedin'

# Custom vars
version: 0.1.0

plugins:
  - jekyll-paginate

google_analytics: 'G-3MZE8FVD9N'
